# Task 2: Popular areas in NYC

### This task will be done in 2 stages. 
### Stage 1 will be all about data loading, cleaning and preparing,  while the Stage 2 will be data visualization.

### For Stage 1 we will use Python, and for Stage 2 we will use Tableau.

#### Stage 1

In [ ]:
# First of all, we need to import the required libraries.

In [4]:
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
from io import BytesIO
from zipfile import ZipFile
import urllib.request
import os

In [ ]:
# As we want to do the data prep directly from the website(https://s3.amazonaws.com/tripdata/index.html).
# Instead of manualy downloading all zip files we will use the following commands bellow 
# (To successfully run the code bellow , you will need to have chromedriver downloaded and extracted to the navigated path)

In [5]:
browser = webdriver.Chrome('C:/Users/Ilija/chromedriver/chromedriver')
browser.get('https://s3.amazonaws.com/tripdata/index.html')

In [6]:
all_links = [link.get_attribute('href') for link in browser.find_elements_by_tag_name('a')]

In [ ]:
# We will use the data for year 2017 and 2018, in the code bellow we are extracting the necessary data from the provided links.

In [7]:
linksJC_17 = [link for link in all_links if 'JC' in link if '2017' in link]
linksJC_18 = [link for link in all_links if 'JC' in link if '2018' in link]
links_17 = [link for link in all_links if 'JC' not in link if '2017' in link]
links_18 = [link for link in all_links if 'JC' not in link if '2018' in link]

In [ ]:
# Now we need to create a function to download, unzip and dataframe the data from the links.

In [8]:
def create_df(link):
    
    url = urllib.request.urlopen(link)
    output = open('temporary.zip', 'wb')    
    output.write(url.read())
    output.close()
    dataframe = pd.read_csv('temporary.zip')
    
    if (len(dataframe.columns) == 15):
        dataframe.columns = ['Trip Duration (sec)', 'Start Time', 'Stop Time', 'Start Station ID',
       'Start Station Name', 'Start Station Latitude',
       'Start Station Longitude', 'End Station ID', 'End Station Name',
       'End Station Latitude', 'End Station Longitude', 'Bike ID', 'User Type',
       'Birth_Year', 'Gender']
    else:
        dataframe.columns = ['Trip Duration (sec)', 'Start Time', 'Stop Time', 'Start Station ID',
       'Start Station Name', 'Start Station Latitude',
       'Start Station Longitude', 'End Station ID', 'End Station Name',
       'End Station Latitude', 'End Station Longitude', 'Bike ID',
       'Localized Value', 'User Type', 'Birth_Year', 'Gender']
        dataframe = dataframe.drop('Localized Value',1)
        
    print(link)
    os.remove('temporary.zip')
    
    return dataframe

In [ ]:
# We also need to create a function to clean and prepare the dataframe. 
# We will be dropping the n/a values if there are any, we will change the datatypes if they are incorrectly assigned,
# and we will exclude the citizens that are more than 90 years old, because if there is any value >90, it is probably a anomaly.

In [9]:
def prepare_df(df):
    
#     drop n/a
    df = df.dropna(how='any').reset_index(drop=True)
    
#     change data types
    df['Birth_Year'] = df.Birth_Year.astype(int)
    df['Start Time'] = pd.to_datetime(df['Start Time'])
    df['Stop Time'] = pd.to_datetime(df['Stop Time'])
    
#     add Dge column
    df['Age'] = 2018 - df['Birth_Year']
    
#     exclude ages > 90 years
    df = df[df['Age'] < 90]
    
    return df

In [ ]:
# Now we need to create empy dataframes in which we will store our values.

In [10]:
ny17 = pd.DataFrame()
ny18 = pd.DataFrame()

In [ ]:
# Bellow we will append the values to the newly created dataframes, this process might take a while.

In [11]:
for link in links_17:
    temporary_df = create_df(link)
    ny17 = ny17.append(temporary_df, ignore_index=True, sort=False)

https://s3.amazonaws.com/tripdata/201701-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201702-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201703-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201704-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201705-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201706-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201707-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201708-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201709-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201710-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201711-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201712-citibike-tripdata.csv.zip

In [12]:
for link in links_18:
    temporary_df = create_df(link)
    ny18 = ny18.append(temporary_df, ignore_index=True, sort=False)

https://s3.amazonaws.com/tripdata/201801-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201802-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201803-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201804-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201805-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201806-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201807-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201808-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201809-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201810-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201811-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201812-citibike-tripdata.csv.zip

In [13]:
ny17 = prepare_df(ny17)
ny18 = prepare_df(ny18)

In [20]:
# In the 2 cells bellow, we are extracting the first 5 results from our table, to get a glimpse of our newly formed tables.

In [14]:
ny17.head()

,Trip Duration (sec),Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth_Year,Gender,Age
0,680,2017-01-01 00:00:21,2017-01-01 00:11:41,3226,W 82 St & Central Park West,40.782750,-73.971370,3165,Central Park West & W 72 St,40.775794,-73.976206,25542,Subscriber,1965,2,53
1,1282,2017-01-01 00:00:45,2017-01-01 00:22:08,3263,Cooper Square & E 7 St,40.729236,-73.990868,498,Broadway & W 32 St,40.748549,-73.988084,21136,Subscriber,1987,2,31
2,666,2017-01-01 00:01:51,2017-01-01 00:12:57,3163,Central Park West & W 68 St,40.773407,-73.977825,3163,Central Park West & W 68 St,40.773407,-73.977825,16050,Subscriber,2000,1,18
3,559,2017-01-01 00:05:00,2017-01-01 00:14:20,499,Broadway & W 60 St,40.769155,-73.981918,479,9 Ave & W 45 St,40.760193,-73.991255,27294,Subscriber,1973,1,45
4,826,2017-01-01 00:05:37,2017-01-01 00:19:24,362,Broadway & W 37 St,40.751726,-73.987535,445,E 10 St & Avenue A,40.727408,-73.981420,23288,Subscriber,1977,2,41

In [15]:
ny18.head()

,Trip Duration (sec),Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth_Year,Gender,Age
0,970,2018-01-01 13:50:57.434,2018-01-01 14:07:08.186,72.0,W 52 St & 11 Ave,40.767272,-73.993929,505.0,6 Ave & W 33 St,40.749013,-73.988484,31956,Subscriber,1992,1,26
1,723,2018-01-01 15:33:30.182,2018-01-01 15:45:33.341,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3255.0,8 Ave & W 31 St,40.750585,-73.994685,32536,Subscriber,1969,1,49
2,496,2018-01-01 15:39:18.337,2018-01-01 15:47:35.172,72.0,W 52 St & 11 Ave,40.767272,-73.993929,525.0,W 34 St & 11 Ave,40.755942,-74.002116,16069,Subscriber,1956,1,62
3,306,2018-01-01 15:40:13.372,2018-01-01 15:45:20.191,72.0,W 52 St & 11 Ave,40.767272,-73.993929,447.0,8 Ave & W 52 St,40.763707,-73.985162,31781,Subscriber,1974,1,44
4,306,2018-01-01 18:14:51.568,2018-01-01 18:19:57.642,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3356.0,Amsterdam Ave & W 66 St,40.774667,-73.984706,30319,Subscriber,1992,1,26

In [21]:
# In 2 cells bellow, we are checking for the data types in our new tables.

In [16]:
ny17.dtypes

Trip Duration (sec)                 int64
Start Time                 datetime64[ns]
Stop Time                  datetime64[ns]
Start Station ID                    int64
Start Station Name                 object
Start Station Latitude            float64
Start Station Longitude           float64
End Station ID                      int64
End Station Name                   object
End Station Latitude              float64
End Station Longitude             float64
Bike ID                             int64
User Type                          object
Birth_Year                          int32
Gender                              int64
Age                                 int32
dtype: object

In [17]:
ny18.dtypes

Trip Duration (sec)                 int64
Start Time                 datetime64[ns]
Stop Time                  datetime64[ns]
Start Station ID                  float64
Start Station Name                 object
Start Station Latitude            float64
Start Station Longitude           float64
End Station ID                    float64
End Station Name                   object
End Station Latitude              float64
End Station Longitude             float64
Bike ID                             int64
User Type                          object
Birth_Year                          int32
Gender                              int64
Age                                 int32
dtype: object

In [23]:
# We are appending 2 tables to see how big our table is.

In [19]:
nydf = ny17.append(ny18, ignore_index=True, sort=False)

In [22]:
nydf.count()

Trip Duration (sec)        32242413
Start Time                 32242413
Stop Time                  32242413
Start Station ID           32242413
Start Station Name         32242413
Start Station Latitude     32242413
Start Station Longitude    32242413
End Station ID             32242413
End Station Name           32242413
End Station Latitude       32242413
End Station Longitude      32242413
Bike ID                    32242413
User Type                  32242413
Birth_Year                 32242413
Gender                     32242413
Age                        32242413
dtype: int64

In [ ]:
# We will now download our prepared dataset as csv file.

In [ ]:
nydf.to_csv('citibikeDATA.csv', encoding='utf-8', index=False)

## With the above download, our Stage 1 is now completed. We have sucesfully prepared our data for the Stage 2. 
## Stage 2 will be done in Tableau, as Tableau can do much better job with visualization than the Python libraries.

In [8]:
# As our main goal was to see what were the most popular areas, I have created Top 10 chart bellow.
# From the table bellow, we can see that the most popular Start-End trip was from Hamilton Park to Grove St Path, 
# and that the least popular was Essex Light Rail - Sip Ave.

![](png/startend.png)

In [9]:
# From the table bellow, we can see that Groove St Path is the most popular start station with 83902 trips, 
# while the JCBS Depot is the least popular station with only 39 trips.

![](png/Top10.png)

In [12]:
# From the table bellow we can see that the most popular end station was Grove St Path with 107963 trips in, 
# while there are several of least popular end stations.

![](png/end.png)

In [13]:
# From the table bellow we can see the popularity of our stations by month. 
# We see that the most hits are from the early summer until the October, as the weather for biking is really good at that time of the year.

![](png/bymonth.png)

In [17]:
# The table bellow shows us the busiest time of the day for bike trips. 
# We can see that the busiest times are from 7:00 and 8:00 in the morning, and 17:00 and 18:00 in the afternoon. 
# As the most people work from 8,9 until 16,17 it seems that they are opting to go to their work with bikes.

![](png/peakhours.png)

In [20]:
# Bellow is the visualization graph of our trips. As we mentioned before,
# Groove St Path is the most popular start station with 83902 trips

![](png/outdots.png)

In [24]:
# Bellow is the visualization graph of our  end trips. Grove St Path is also the most popular end trip station 
# with 107963 trips.

![](png/indots.png)

## That concludes our stage 2 and our Task 2. I hope that you have gained some insight from the data provided.